spring.application.name=ecommerce-backend
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
#connect to mySql database
spring.datasource.username=root
#this is used as a user name to database
spring.datasource.password=haranadh
#this password for the mysql database
spring.jpa.hibernate.ddl-auto=update
#it does the process like update or create or all sql process
spring.jpa.show-sql=true
# this prints the sql queries in the console
spring.jpa.properties.hibernate.format_sql=true
#this makes sql easier to read
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080

